$(document).ready(main);var cond=1;function main(){document.getElementsByTagName('body')[0].style.visibility='terlihat'
if($('. entry-content').text().length<500){$('. entry-content').css('padding-bottom','20px');$('. post- footer .social ').hide()};var imgclass=$('. post-body ')[' find '](' img: first ');$(imgclass)[' parent ']()[' addClass ']('menghapus')
$("a").has("img").addClass("imglink");if($('. header-navigationx li: has (ul)')){$('. header-navigationx li: has (ul) ')[' temukan '](' a: pertama ')[' tambahkan '](' <i class = "fa fa-caret-down caret" aria-hidden = "true"> </i> ')}
var date=Date baru();var year=date.getFullYear();document.getElementById('site-year')['innerHTML']=tahun
$('. header-navigationx ul').find('li: memiliki (ul)').anak-anak('a').removeAttr('href');$('. header-navigationx li: has (ul) ').klik(function(){$(this).children(' ul ').slideToggle()});$('. bt-menu ').klik(function(){$(' header nav ').slideToggle()});$('. search-icon').klik(fungsi(e){$('. search-box').slideToggle(0);e.preventDefault()});var menu=jQuery('header nav');jQuery(window).on('resize',function(){if(!jQuery(". menu-bar").adalah(": visible")&&!menu.is(' :terlihat'))
{menu.css({'display':''})}});$('. item-content').masing-masing(function(){if($(this).find('img').length){$('. PopularPosts ul').Css({'list-style':'none','padding':'0'})}});$('. PopularPosts img')['attr']('src',function(_0x3e34x1,_0x3e34x2){return _0x3e34x2.replace('w72-h72-p-nu','s130')})}
fungsi removeURLParameter(url,parameter){var urlparts=url.split('?');if(urlparts.length>=2){awalan var=encodeURIComponent(parameter)+'=';var pars=urlparts[1].split(/[&;]/g);untuk(var i=pars.length;i->0;){if(pars[i].lastIndexOf(awalan,0)!==-1){pars.sambatan(i,1)}}
url=urlparts[0]+(pars.length>0?'?'+pars.join('&'):"");return url}else{return url}}
function createThumb(pID,pURL){var div=document.getElementById(pID);var imgtag="";var img=div.getElementsByTagName("img");var vid1=div.getElementsByTagName("iframe");jika(img.length>=1){imgtag='<a href="'+pURL+'"> <div class = "img-div" style = "gambar latar belakang: url ('+img[0].src+') ; "> </div> </a> ';div.innerHTML=imgtag}
lain jika(div.innerHTML.indexOf("https://www.youtube.com/embed/")!=-1){var vidid1=vid1[0].src;var vidfiler=vidid1.substring(vidid1.indexOf("https://www.youtube.com/embed/")+29);var vidid=" ";vidid=removeURLParameter(vidfiler," rel ");vidid=removeURLParameter(vidid," fitur ");imgtag='<meta itemprop = "image" content = "https://i1.ytimg.com/vi'+vidid+'/sddefault.jpg"> </meta> <meta itemprop = "image_url" content = "https: // i1.ytimg.com/vi'+vidid+'/sddefault.jpg"></meta><div class = "youtube-post-format"> <a href="'+pURL+'"> <div class = "img -div "style =" background-image: url (https://i1.ytimg.com/vi'+vidid+'/sddefault.jpg); "> <div class =" thumb-overlay "> <div class = "vertical-align"> <svg height = "100%" versi = "1.1" viewBox = "0 0 68 48" width = "100%"> <path class = "ytp-large-play- tombol-bg "d =" m .66,37.62 c 0,0 .66,4.70 2.70,6.77 2.58.2.71 5.98.2.63 7.49.2.91 5.43, .52 23.10, .68 23.12, .68 .00, -1.3e -5 14.29, -0.02 23.81, -0.71 1.32, -0.15 4.22, -0.17 6.81, -2.89 2.03, -2.07 2.70, -6.77 2.70, -6.77 0,0 .67, -5.52 .67, -11.04 l 0, -5.17 c 0, -5.52 -0.67, -11.04 -0.67, -11.04 0,0 -0.66, -4.70 -2.70, -6.77 C 62.03, .86 59.13, .84 57.80, .69 48.28.0 34.00.0 34.00 , 0 33.97.0 19.69.0 10.18, .69 8.85, .84 5.95, .86 3.36.3.58 1.32.5.65 .66, 10.35 .66, 10.35 c 0,0 -0.55.4.50 -0.66.9.45 l 0.8.36 c .10,4,94 .66,9.45 .66,9.45 z "fill =" # 1f1f1e "fill-opacity =" 0.81 "> </path> <path d =" m 26.96,13.67 18.37.9.62 -18.37.9.55 - 0.00, -19.17 z "fill =" # fff "> </path> <path d =" M 45.02,23.46 45.32,23.28 26.96,13.67 43.32, 24.34 45.02,23.46 z "fill =" # ccc "> </ path > </svg> </div> </div> </a> </div> </div> ';div.innerHTML=imgtag}
lain{div.innerHTML=imgtag}}
$(document).ready(function(){$('article').not(': has (.img-div)').addClass('format-standard');$('article: has (.img -div) ').addClass(' post-format-image ');$('. search-icon ').on(' klik ',fungsi(event){$(' # search ').addClass(' open ');$(' # search> form> input [type = "search"] ').focus()});$(' # search, #search button.close ').on(' klik keyup ',fungsi(event){if(event.target==ini||event.target.className=='search-close'||event.keyCode==27){$(ini).removeClass('open')}})})
